map_server:
    ros__parameters:
        frame_id: map
        topic_name: map
        use_sim_time: true
        yaml_filename: /home/ros2/ros1_2_ros2_ws/src/nav2_launch_files/maps/231128_2_delta_8f.yaml