standalone_tags:
  [
    {id: 0, size: 0.04},
    {id: 1, size: 0.04},
    {id: 2, size: 0.04},
    {id: 3, size: 0.04},
  ]
tag_bundles:
  [
    {
      name: 'docking_0',
      layout:
        [
          {id: 0, size: 0.04, x: -0.0750, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 1, size: 0.04, x: -0.0250, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 2, size: 0.04, x: 0.0250 , y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 3, size: 0.04, x: 0.0750 , y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
        ]
    }
  ]
