standalone_tags:
  [
    {id: 0, size: 0.105},
    {id: 1, size: 0.05}
  ]
# tag_bundles:
#   [
#     {
#       name: 'charging_0',
#       layout:
#         [
#           {id: 0, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
#         ]
#     }
#   ]
